export const ENLocalizedStrings = {
  GlobalLabels: {
    Other: "Other",
    Store: "Store",
    Staff: "Staff",
    Welcome: "Login to CMS",
    Balance: "Balance",
    Authorize: "Authorization",
    Carrier: "Internet Service Provider",
    Topup: "Add balance",
    Close: "Close",
    All: "All",
    STT: "No.",
    NoSort: "None",
    Status: "Status",
    Phone: "Phone Number",
    Noti: "Notification",
    Actions: "Actions",
    Active: "Active",
    Position: "Position",
    Inactive: "Inactive",
    Deleted: "Delete",
    Search: "Search",
    Redo: "Refresh Filter",
    Cancel: "Cancel",
    Error: "Something is error. Please try again",
    TakePicture: "Take picture",
    Confirmed: "Confirm",
    Detail: "Details",
    Create: "Add new",
    Password: "Password",
    NewPassword: "New password",
    PasswordConfirmed: "Confirm password",
    Description: "Description",
    Update: "Update",
    Address: "Address",
    Partner: "Partner",
    PartnerCode: "PartnerCode",
    Total: "Total",
    NoPartner: "Not a partner",
    createdAt: "Created date",
    updatedAt: "Updated date",
    Cover: "Background image",
    Success: "Success",
    Failed: "Failed",
    Date: "Date",
    Week: "Week",
    Month: "Month",
    Hour: "Hour",
    ExcelExporting: "Export Excel",
    Type: "Type",
    Name: "Name",
    Fullname: "Full name",
    Regions: "Region",
    Login: "Login",
    NoInfo: "No information",
    ASC: "Ascending",
    DESC: "Descending",
    Logout: "Logout",
    Attention: "See notes here",
    ReloadImages: "Refresh image",
    DownloadImage: "Download image",
    DownloadZip: "Download zip file",
    Placeholder: "Import",
    Choose: "Select",
    Images: "Image",
    UserName: "Username",
    Email: "Email",
    Order: "STT",
    Loading: "Loading...",
    Time: "Time",
    Yes: "Yes",
    No: "No",
    Download: "Download",
    User: "User",
    Config: "Configuration",
    Save: "Save",
    Edit: "Edit",
    Supplier: "Supplier",
    SupplierType: "NCC Type",
    Import: "Import",
    ChangeStatus: "Change status",
    AccountManagement: "Account management",
    ResetPassword: "Reset password",
    Tools: "Tools",
    Reason: "Reason",
    RefreshFeature: "Refresh permission data",
  },
  GlobalMessage: {
    RightClickCopy: "Right click to copy",
    ApproveAksing: "Do you want to approve this element ?",
    Email: "Enter the correct Email format!",
    UpdateSuccessfully: "Updated successfully!",
    UpdateFailed: "Updated failed:",
    CreateSuccessfully: "Created successfully!",
    CreateFailed: "Created failed:",
    DeleteSuccessfully: "Delete successfully!",
    DeleteFailed: "Delete failed:",
    DeleteConfirmation: "Confirm deleting this element?",
    DeleteConfirmationWithName: 'Do you want to delete "{name}"?',
    ResetPassSuccessfully: "Reset password successfully!",
    ResetPassFailed: "Reset password failed:",
    Error: "An error occurred",
    Exporting: "Exporting Report...",
    SystemError:
      "Error retrieving login information or expired token, returning to login page...",
    LoginSuccessfully: "Login successfully!",
    InvalidAccount: "Invalid username or password or User does not exist!",
    InvalidMenuConfig: "Error in getting Sidebar Menu, please try again later!",
    Supplier: "Please enter Reference Code",
    ChooseSupplier: "Please select Supplier",
    Required: "Please enter this information",
    CannotAccessCam: "Cannot access camera",
    SavingForLogin: "Keep me logged in",
    SavedToClipboard: "Saved value to clipboard.",
    InvalidStore: "Choose a specific store",
    InvalidToken: "Token is invalid or removed, directing to Login...",
    PasswordNotMatch: "Password does not match",
    PasswordLength: "Password needs to be at least 6 characters",
    ResetPassMessage: "Do you want to change password for this user?",
    SyncOnProcess: "Syncing data, please wait...",
    NotAllowedToUse: "Need to be authorized",
    RefreshFeatureSuccessfully:
      "Permission data of your account has been refreshed !",
    NotFoundPath: "Not found path or unable to access api",
    AlreadyHasCopied: "This value has been saved",
    ResetOTPMessage: "Do you want to reset OTP for this user?",
    SearchPlaceholder: "Enter keywords to search",
    ExcelError: "Error with files: Wrong formats or invalid data",
    NeedPermisson: "Your permisson to read clipboard must be granted",
    SignUp: "Sign up account",
    Url: "Enter value following the URL format",
    PositiveNumber: "Enter the value from 0...",
    Currency: "Enter the money at least 1,000 VND...",
  },
  GlobalPlaceholder: {
    UserName: "Enter user name",
    Email: "Please enter email...",
    Name: "Please enter name...",
    Code: "Please enter code...",
    Partner: "Please select partner",
    Status: "Please select status",
    Phone: "Please enter phone number...",
    Password: "Enter password",
    PasswordConfirmed: "The confirmation password must match the password",
    Description: "Please enter description in text",
    Type: "Please select type",
  },
  GlobalTotalSummary: {
    Success: "Success",
    Error: "Failed",
    Other: "Others",
    Revenue: "Total revenue",
  },
  GlobalService: {
    SIM_ECOMMERCE: "SIM",
    TRAVEL_SIM: "Travel SIM",
    NICE_SIM: "Nice SIM",
    BUY_PACKAGE: "Mobile Plan",
    AIR_TIME: "Top up phone",
    ALL: "All",
  },
};
