export const VNLocalizedStrings = {
  GlobalLabels: {
    Other: "Khác",
    Store: "Cửa hàng",
    Staff: "Nhân viên",
    Welcome: "Đăng nhập CMS",
    Balance: "Hạn mức",
    Authorize: "Uỷ quyền",
    Carrier: "Nhà mạng",
    Topup: "Nạp",
    STT: "STT",
    All: "Tất cả",
    NoSort: "Không có",
    Close: "Đóng",
    Status: "Trạng thái",
    Phone: "Số điện thoại",
    Actions: "Hành động",
    Active: "Hoạt động",
    Inactive: "Không hoạt động",
    Deleted: "Xóa",
    TakePicture: "Chụp ảnh",
    Noti: "Thông báo",
    Search: "Tra cứu",
    Position: "Vị trí",
    Redo: "Xóa bộ lọc",
    Cancel: "Hủy",
    Error: "Có lỗi xảy ra. Vui lòng thử lại",
    Confirmed: "Xác nhận",
    Detail: "Chi tiết",
    Create: "Thêm mới",
    Password: "Mật khẩu",
    NewPassword: "Mật khẩu mới",
    PasswordConfirmed: "Xác nhận mật khẩu",
    Description: "Mô tả",
    Update: "Cập nhật",
    Address: "Địa chỉ",
    Partner: "Đối tác",
    PartnerCode: "Mã đối tác",
    Total: "Tổng cộng",
    NoPartner: "Không thuộc đối tác",
    createdAt: "Ngày tạo",
    updatedAt: "Ngày cập nhật",
    Cover: "Ảnh nền",
    Success: "Thành công",
    Failed: "Thất bại",
    Date: "Ngày",
    Week: "Tuần",
    Month: "Tháng",
    Hour: "Giờ",
    ExcelExporting: "Xuất Excel",
    Type: "Loại",
    Name: "Tên",
    Fullname: "Họ và tên",
    Regions: "Vùng",
    Login: "Đăng nhập",
    NoInfo: "Không có thông tin",
    ASC: "Tăng dần",
    DESC: "Giảm dần",
    Logout: "Đăng xuất",
    Attention: "Xem lưu ý tại đây",
    ReloadImages: "Làm mới ảnh",
    DownloadImage: "Tải ảnh",
    DownloadZip: "Tải file zip",
    Placeholder: "Nhập ",
    Choose: "Chọn ",
    Images: "Hình ảnh",
    UserName: "Tên tài khoản",
    Email: "Email",
    Order: "STT",
    Loading: "Loading...",
    Time: "Thời gian",
    Yes: "Có",
    No: "Không",
    Download: "Tải xuống",
    User: "Người dùng",
    Config: "Cấu hình",
    Save: "Lưu",
    Edit: "Chỉnh sửa",
    Supplier: "Nhà cung cấp",
    SupplierType: "Loại NCC",
    Import: "Nhập",
    ChangeStatus: "Đổi trạng thái",
    AccountManagement: "Quản lý tài khoản",
    ResetPassword: "Đặt lại mật khẩu",
    Tools: "Công cụ",
    Reason: "Lý do",
    RefreshFeature: "Làm mới quyền truy cập",
  },
  GlobalMessage: {
    RightClickCopy: "Chuột phải để sao chép",
    ApproveAksing: "Bạn xác nhận duyệt phần tử này ?",
    Email: "Nhập đúng định dạng Email !",
    UpdateSuccessfully: "Cập nhật thành công !",
    UpdateFailed: "Cập nhật thất bại:",
    CreateSuccessfully: "Tạo mới thành công !",
    CreateFailed: "Tạo mới thất bại:",
    DeleteSuccessfully: "Xóa thành công !",
    DeleteFailed: "Xóa thất bại:",
    DeleteConfirmation: "Xác nhận xóa phần tử này ?",
    DeleteConfirmationWithName: 'Bạn có chắc chắn muốn xóa "{name}"?',
    ResetPassSuccessfully: "Đặt lại mật khẩu thành công !",
    ResetPassFailed: "Đặt lại mật khẩu thất bại:",
    Error: "Đã có lỗi xảy ra",
    Exporting: "Đang xuất Báo cáo...",
    SystemError:
      "Có lỗi lấy thông tin đăng nhập hoặc token hết hạn, quay lại trang đăng nhập...",
    LoginSuccessfully: "Đăng nhập thành công !",
    InvalidAccount:
      "Tên tài khoản hoặc mật khẩu không đúng hoặc User không tồn tại !",
    InvalidMenuConfig:
      "Lỗi không lấy được Menu Sidebar, vui lòng thử lại sau !",
    Supplier: "Vui lòng nhập Mã tham chiếu",
    ChooseSupplier: "Vui lòng chọn Nhà cung cấp",
    Required: "Vui lòng nhập thông tin này",
    CannotAccessCam: "Không thể truy cập máy ảnh",
    SavingForLogin: "Giữ cho lần đăng nhập tiếp theo",
    SavedToClipboard: "Đã lưu giá trị vào bộ nhớ tạm.",
    InvalidStore: "Chọn một cửa hàng",
    InvalidToken:
      "Token không khả dụng hoặc không tồn tại, quay lại Đăng nhập...",
    PasswordNotMatch: "Mật khẩu không trùng khớp",
    PasswordLength: "Mật khẩu phải từ 6 ký tự trở lên",
    ResetPassMessage: "Bạn có muốn đổi mật khẩu cho người dùng này không?",
    SyncOnProcess: "Đang đồng bộ trạng thái, vui lòng đợi...",
    NotAllowedToUse: "Cần cấp quyền",
    RefreshFeatureSuccessfully: "Đã làm mới quyền truy cập của tài khoản !",
    NotFoundPath: "Không tìm thấy đường dẫn hoặc không có quyền truy cập",
    AlreadyHasCopied: "Đã có giá trị trong bộ nhớ tạm",
    ResetOTPMessage: "Bạn có muốn đặt lại OTP cho người dùng này không?",
    SearchPlaceholder: "Nhập từ khóa để tìm kiếm",
    ExcelError: "Lỗi xuất file: Sai định dạng hoặc không có dữ liệu",
    NeedPermisson: "Vui lòng cấp quyền truy cập bộ nhớ tạm",
    SignUp: "Đăng ký tài khoản",
    Url: "Nhập giá trị dưới định dạng URL",
    PositiveNumber: "Nhập giá trị từ 0 trở lên...",
    Currency: "Nhập giá tiền ít nhất 1,000 VND",
  },
  GlobalPlaceholder: {
    UserName: "Nhập tên tài khoản",
    Email: "Vui lòng nhập email...",
    Name: "Vui lòng nhập tên...",
    Code: "Vui lòng nhập mã...",
    Partner: "Vui lòng chọn đối tác",
    Status: "Vui lòng chọn trạng thái",
    Phone: "Vui lòng nhập số điện thoại...",
    Password: "Nhập mật khẩu",
    PasswordConfirmed: "Mật khẩu xác nhận cần trùng với mật khẩu",
    Description: "Vui lòng nhập mô tả là chữ",
    Type: "Vui lòng chọn loại",
  },
  GlobalTotalSummary: {
    Success: "Thành công",
    Error: "Thất bại",
    Other: "Khác",
    Revenue: "Tổng doanh thu",
  },
  GlobalService: {
    SIM_ECOMMERCE: "SIM",
    TRAVEL_SIM: "SIM Du lịch",
    NICE_SIM: "SIM Số đẹp",
    BUY_PACKAGE: "Gói cước",
    AIR_TIME: "Nạp tiền ĐT",
    ALL: "Tất cả",
  },
};
